# Generated by Django 4.0.5 on 2022-06-11 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodtypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('price', models.PositiveIntegerField(default=None)),
                ('image', models.ImageField(upload_to='dishes/files/covers')),
                ('foodtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='foodtypes.foodtype')),
            ],
        ),
    ]
