# Generated by Django 4.0.5 on 2022-06-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtypes', '0001_initial'),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='foodtypes',
            field=models.ManyToManyField(related_name='menus', to='foodtypes.foodtype'),
        ),
    ]
