# Generated by Django 4.0.5 on 2022-06-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
