# Generated by Django 4.0.5 on 2022-06-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_date_alter_booking_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(),
        ),
    ]
