# Generated by Django 4.0.5 on 2022-06-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.PositiveBigIntegerField(default=None),
        ),
    ]
